name: Deploy

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

jobs:
  test:
    uses: ./.github/workflows/sbt-test.yaml

  build:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Build JAR
        run: sbt assembly

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: FireSim
          path: target/scala-3.3.6/*.jar

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          generate_release_notes: true
          files: target/scala-3.3.6/*.jar
